# https://github.com/sameersbn/docker-gitlab
version: '2'

services:
  redis:
    restart: always
    image: sameersbn/redis:latest
    command:
      - --loglevel warning
    volumes:
      - /data/gitlab/redis:/var/lib/redis

  mysql:
    restart: always
    image: sameersbn/mysql:latest
    volumes:
      - /data/gitlab/mysql:/var/lib/mysql
    environment:
      - DB_NAME=gitlabhq_production
      - DB_USER=root
      - DB_PASS=123456

  gitlab:
    restart: always
    image: sameersbn/gitlab:10.5.1
    depends_on:
      - redis
    volumes:
      - /data/gitlab/gitlab:/home/git/data
    ports:
      - "10080:80"
      - "10022:22"
    environment:
      - DEBUG=false
      - TZ=Asia/Chongqing
      - GITLAB_TIMEZONE=Chongqing

      - GITLAB_PORT=10080
      - GITLAB_SSH_PORT=10022
      - GITLAB_HOST=localhost

      - DB_ADAPTER=mysql2
      - DB_HOST=mysql
      - DB_NAME=gitlabhq_production
      - DB_USER=root
      - DB_PASS=123456
      - REDIS_HOST=redis
      - REDIS_PORT=6379

      - SMTP_ENABLED=true
      # - SMTP_DOMAIN=www.example.com
      - SMTP_HOST=smtp.partner.outlook.cn
      - SMTP_PORT=587
      - SMTP_USER=lishijun@sensefun.com
      - SMTP_PASS=Qwer1234
      - SMTP_STARTTLS=true
      - SMTP_AUTHENTICATION=login
      # - GITLAB_EMAIL=notifications@example.com
      # - GITLAB_EMAIL_REPLY_TO=noreply@example.com
      # - GITLAB_INCOMING_EMAIL_ADDRESS=reply@example.com

      - GITLAB_SECRETS_DB_KEY_BASE=LhfRbJWqJN3Ts9MqJtqs7CP9bMpvnvFhfnfHwxwpm4rpbV37qr9h3hH3XFqKLXVF
      - GITLAB_SECRETS_SECRET_KEY_BASE=LhfRbJWqJN3Ts9MqJtqs7CP9bMpvnvFhfnfHwxwpm4rpbV37qr9h3hH3XFqKLXVF
      - GITLAB_SECRETS_OTP_KEY_BASE=LhfRbJWqJN3Ts9MqJtqs7CP9bMpvnvFhfnfHwxwpm4rpbV37qr9h3hH3XFqKLXVF

      # - GITLAB_HTTPS=false
      # - SSL_SELF_SIGNED=false

      # - GITLAB_ROOT_PASSWORD=
      # - GITLAB_ROOT_EMAIL=

      # - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
      # - GITLAB_NOTIFY_PUSHER=false

      # - GITLAB_BACKUP_SCHEDULE=daily
      # - GITLAB_BACKUP_TIME=01:00

      # - IMAP_ENABLED=false
      # - IMAP_HOST=imap.gmail.com
      # - IMAP_PORT=993
      # - IMAP_USER=mailer@example.com
      # - IMAP_PASS=password
      # - IMAP_SSL=true
      # - IMAP_STARTTLS=false

      # - OAUTH_ENABLED=false
      # - OAUTH_AUTO_SIGN_IN_WITH_PROVIDER=
      # - OAUTH_ALLOW_SSO=
      # - OAUTH_BLOCK_AUTO_CREATED_USERS=true
      # - OAUTH_AUTO_LINK_LDAP_USER=false
      # - OAUTH_AUTO_LINK_SAML_USER=false
      # - OAUTH_EXTERNAL_PROVIDERS=

      # - OAUTH_CAS3_LABEL=cas3
      # - OAUTH_CAS3_SERVER=
      # - OAUTH_CAS3_DISABLE_SSL_VERIFICATION=false
      # - OAUTH_CAS3_LOGIN_URL=/cas/login
      # - OAUTH_CAS3_VALIDATE_URL=/cas/p3/serviceValidate
      # - OAUTH_CAS3_LOGOUT_URL=/cas/logout

      # - OAUTH_GOOGLE_API_KEY=
      # - OAUTH_GOOGLE_APP_SECRET=
      # - OAUTH_GOOGLE_RESTRICT_DOMAIN=

      # - OAUTH_FACEBOOK_API_KEY=
      # - OAUTH_FACEBOOK_APP_SECRET=

      # - OAUTH_TWITTER_API_KEY=
      # - OAUTH_TWITTER_APP_SECRET=

      # - OAUTH_GITHUB_API_KEY=
      # - OAUTH_GITHUB_APP_SECRET=
      # - OAUTH_GITHUB_URL=
      # - OAUTH_GITHUB_VERIFY_SSL=

      # - OAUTH_GITLAB_API_KEY=
      # - OAUTH_GITLAB_APP_SECRET=

      # - OAUTH_BITBUCKET_API_KEY=
      # - OAUTH_BITBUCKET_APP_SECRET=

      # - OAUTH_SAML_ASSERTION_CONSUMER_SERVICE_URL=
      # - OAUTH_SAML_IDP_CERT_FINGERPRINT=
      # - OAUTH_SAML_IDP_SSO_TARGET_URL=
      # - OAUTH_SAML_ISSUER=
      # - OAUTH_SAML_LABEL="Our SAML Provider"
      # - OAUTH_SAML_NAME_IDENTIFIER_FORMAT=urn:oasis:names:tc:SAML:2.0:nameid-format:transient
      # - OAUTH_SAML_GROUPS_ATTRIBUTE=
      # - OAUTH_SAML_EXTERNAL_GROUPS=
      # - OAUTH_SAML_ATTRIBUTE_STATEMENTS_EMAIL=
      # - OAUTH_SAML_ATTRIBUTE_STATEMENTS_NAME=
      # - OAUTH_SAML_ATTRIBUTE_STATEMENTS_FIRST_NAME=
      # - OAUTH_SAML_ATTRIBUTE_STATEMENTS_LAST_NAME=

      # - OAUTH_CROWD_SERVER_URL=
      # - OAUTH_CROWD_APP_NAME=
      # - OAUTH_CROWD_APP_PASSWORD=

      # - OAUTH_AUTH0_CLIENT_ID=
      # - OAUTH_AUTH0_CLIENT_SECRET=
      # - OAUTH_AUTH0_DOMAIN=

      # - OAUTH_AZURE_API_KEY=
      # - OAUTH_AZURE_API_SECRET=
      # - OAUTH_AZURE_TENANT_ID=
