# https://hub.docker.com/r/zabbix/zabbix-agent/
version: '2'
services:
  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-3.2.4
    restart: always
    ports:
      - "10050:10050"
    volumes:
      - /proc:/data/proc
      - /sys:/data/sys
      - /dev:/data/dev
    environment:
      - ZBX_HOSTNAME=zabbix-agent
      - ZBX_SERVER_HOST=192.168.61.128
      - ZBX_ACTIVESERVERS=zabbix-server:10051